# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-10 08:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumer_id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_user_id', models.IntegerField(default=0)),
                ('consumer_name', models.CharField(default='', max_length=255)),
                ('tag_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer_pass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_user_id', models.IntegerField(default=0)),
                ('pass_master_id', models.IntegerField(default=0)),
                ('corporate_id', models.IntegerField(default=0)),
                ('parking_id', models.IntegerField(default=0)),
                ('parking_lot_id', models.IntegerField(default=0)),
                ('consumer_vehicle_number', models.CharField(default='', max_length=255)),
                ('pass_status', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expire_at', models.DateTimeField(auto_now_add=True)),
                ('start_at', models.DateTimeField(auto_now_add=True)),
                ('is_default', models.CharField(default='', max_length=255)),
                ('payment_status', models.CharField(default='', max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Corporate_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_id', models.IntegerField(default=0)),
                ('corporate_name', models.CharField(default='', max_length=255)),
                ('corporate_contact_number', models.IntegerField(default=0)),
                ('corporate_email', models.EmailField(max_length=255, unique=True)),
                ('corporate_address', models.CharField(default='', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device_Detail_Feed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('lane_id', models.IntegerField(default=0)),
                ('lane_type', models.CharField(max_length=255)),
                ('parking_name', models.CharField(default='', max_length=255)),
                ('parking_id', models.IntegerField(default=0)),
                ('company_id', models.IntegerField(default=0)),
                ('hardware_master_id', models.IntegerField(default=0)),
                ('device_type', models.CharField(default='', max_length=255)),
                ('device_access_address', models.CharField(default='', max_length=255)),
                ('tenant', models.CharField(default='', max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_ping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_user_id', models.IntegerField(default=0)),
                ('tag_id', models.IntegerField(default=0)),
                ('ping_type', models.CharField(default='', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lane_id', models.IntegerField(default=0)),
                ('event_response', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Parking_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.CharField(default='', max_length=255)),
                ('checkout_time', models.CharField(default='', max_length=255)),
                ('pass_status', models.CharField(default='', max_length=255)),
                ('parking_lot_id', models.IntegerField(default=0)),
                ('consumer_user_id', models.IntegerField(default=0)),
                ('company_id', models.IntegerField(default=0)),
                ('bay_id', models.IntegerField(default=0)),
                ('entry_consumer_identification_id', models.CharField(default='', max_length=255)),
                ('exit_consumer_identification_id', models.CharField(default='', max_length=255)),
                ('parking_id', models.IntegerField(default=0)),
                ('lot_type', models.CharField(default='', max_length=255)),
                ('special', models.CharField(default='', max_length=255)),
                ('booking_id', models.IntegerField(default=0)),
                ('entry_lane_id', models.IntegerField(default=0)),
                ('exit_lane_id', models.IntegerField(default=0)),
                ('customer_token', models.IntegerField(default=0)),
                ('tenant', models.CharField(default='', max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pass_access_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(default='', max_length=255)),
                ('start_minute_of_the_day', models.CharField(default='', max_length=255)),
                ('end_minute_of_the_day', models.CharField(default='', max_length=255)),
                ('duration', models.IntegerField(default=0)),
                ('pass_master_id', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('start_day', models.IntegerField(default=0)),
                ('end_day', models.IntegerField(default=0)),
                ('tenant', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VMS_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(default='', max_length=255)),
                ('is_dafault', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
