# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enable_api', '0003_auto_20180510_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer_id',
            name='tag_type',
            field=models.IntegerField(default=0),
        ),
    ]
