# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enable_api', '0004_consumer_id_tag_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer_id',
            name='tag_type',
            field=models.CharField(default='NULL', max_length=255),
        ),
    ]
