# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enable_api', '0005_auto_20180511_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer_pass',
            name='lot_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
